notifier:
  build: kino-notifier
  volumes:
    - ./kino-notifier:/app
  links:
    - stats:stats.local
    - rabbitmq:rabbitmq.local
    - ssh:ssh.local
  volumes_from:
    - ssh
  environment:
    - RABBITMQ_HOST=rabbitmq.local
    - STATSD_HOST=stats.local
ssh:
  build: kino-ssh-server
  ports: 
    - "3500:22"
  volumes:
    - /home
rabbitmq:
  image: rabbitmq:3.5.7
  ports:
    - "5672"
stats:
  image: kamon/grafana_graphite:latest
  ports:
    - "8215/udp"
    - "4002:80"
    - "4003:81"
postgres:
  image: postgres:9.4.5
  ports:
    - "5432"
web:
  build: kino_web
  working_dir: /app/user
  ports:
    - "4000:4000"
  links:
    - postgres:postgres.local
    - rabbitmq:rabbitmq.local
  environment:
    PORT: 4000
    MIX_ENV: dev
    AMQP_URL: amqp://guest:guest@rabbitmq.local
    DATABASE_URL: postgres://postgres:@postgres.local:5432/kino_web_dev
  volumes:
    - ./kino_web:/app/user
