source 'https://rubygems.org'

# Specify your gem's dependencies in notifier.gemspec
gemspec

# Optional development dependencies
group :development do
  gem 'pry-stack_explorer'
  gem 'rb-readline'
end
